---
# handlers file for mesos-slave
- name: Restart mesos-slave
  service: name=mesos-slave state=restarted enabled=yes

- name: Stop mesos-master
  service: name=mesos-master state=stopped enabled=no

- name: Stop zookeeper
  service: name=zookeeper state=stopped enabled=no
  when: ansible_distribution == "Ubuntu"
