---
# tasks file for contrail-agent
- include: "{{ ansible_distribution }}.yml"

- name: Start docker engine
  service: name=docker state=restarted enabled=yes

- name: Pull vrouter insert docker image
  shell: "{{ docker_auth }} docker pull {{ docker_repo }}/centos-vrouter-{{ openstack_version }}:{{ contrail_version }}"

- name: Run vrouter insert docker
  command: docker run -v /lib/modules:/lib/modules --privileged=true --cap-add=AUDIT_WRITE {{ docker_repo }}/centos-vrouter-{{ openstack_version }}:{{ contrail_version }}

- name: Pull agent docker image
  command: "{{ docker_auth }} docker pull {{ docker_repo }}/contrail-agent-{{ openstack_version }}:{{ contrail_version }}"

- name: Run agent docker
  command: docker run -v /lib/modules:/lib/modules --privileged=true --cap-add=AUDIT_WRITE --pid=host --net=host -e CLOUD_ORCHESTRATOR=kubernetes -e CONFIG_IP={{ mesos_master_ip }} -e COMPILE_VROUTER_MODULE=no -e INSTALL_VROUTER_MODULE=yes -e VROUTER_PHYSICAL_INTERFACE=eth0 -dt {{ docker_repo }}/contrail-agent-{{ openstack_version }}:{{ contrail_version }}
