---
# tasks file for contrail-controller
- name: Start docker engine
  command: service docker start

- name: Run controller docker
  command: gcloud docker run --privileged=true --cap-add=AUDIT_WRITE --pid=host --net=host -e CLOUD_ORCHESTRATOR=kubernetes -dt us.gcr.io/rrugge-project/contrail-controller:3.1.1.0-29

- name: Run analytics docker
  command: gcloud docker run --privileged=true --cap-add=AUDIT_WRITE --pid=host --net=host -e CLOUD_ORCHESTRATOR=kubernetes -dt us.gcr.io/rrugge-project/contrail-analytics:3.1.1.0-29
