# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: setup k8s master
  hosts: k8s-master
  roles:
    - role: k8s-master
      k8s_master_hostname: "{{ hostvars[groups['k8s-master'][0]]['ansible_hostname']}}"

- name: setup k8s minion
  hosts: k8s-minion
  roles:
    - role: k8s-minion
      k8s_master_ip: "{{ hostvars[groups['k8s-master'][0]]['ansible_default_ipv4']['address']}}"
      k8s_master_hostname: "{{ hostvars[groups['k8s-master'][0]]['ansible_hostname']}}"
