# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: setup ansible master
  hosts: mesos-master
  roles:
    - role: mesos/mesos-master
    - role: mesos/docker

- name: setup ansible slave
  hosts: mesos-slave
  roles:
    - role: mesos/mesos-slave
      mesos_master_ip: "{{ hostvars[groups['mesos-master'][0]]['ansible_default_ipv4']['address']}}"
    - role: mesos/docker
