---
# handlers file for mesos-master
- name: Restart zookeeper
  service: name=zookeeper state=restarted enabled=yes

- name: Restart mesos-master
  service: name=mesos-master state=restarted enabled=yes

- name: Stop mesos-slave
  service: name=mesos-slave state=stopped enabled=no

- name: Restart marathon
  service: name=marathon state=restarted enabled=yes

- name: Reload systemctl daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'
