---
# tasks file for mesos-slave
- include: "{{ ansible_distribution }}.yml"

- name: Install the latest version of mesos
  package: name=mesos state=latest

- name: Update mesos zookeeper connection config
  template: src=mesos-zk.j2 dest=/etc/mesos/zk
  tags: deploy

- name: Update mesos-slave hostname
  template: src=mesos-slave-hostname.j2 dest=/etc/mesos-slave/hostname
  tags: deploy

- name: Update mesos-slave ip
  template: src=mesos-slave-ip.j2 dest=/etc/mesos-slave/ip
  tags: deploy
  notify:
    - Stop zookeeper
    - Stop mesos-master
    - Restart mesos-slave
