---
- name: Apt with https and install CA certificates
  package: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
  
- name: Add apt-key for docker
  apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80 state=present

- name: Add backports for debian repo
  apt_repository: repo='deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports main' state=present

- name: Add docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-{{ ansible_distribution_release }} main' state=present

- name: Update cache apt-get update
  apt: update_cache=yes
