---
# tasks file for mesos-master
- include: "{{ ansible_distribution }}.yml"

- name: Install mesos and marathon
  package: pkg={{ item }} state=latest
  with_items:
    - mesos
    - marathon

- name: Update mesos zookeeper connection config
  template: src=mesos-zk.j2 dest=/etc/mesos/zk
  tags: deploy

- name: Update zookeeper config myid
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  tags: deploy

- name: Update zookeeper config zoo.cfg
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  tags: deploy

- name: Update mesos-master ip
  template: src=mesos-master-ip.j2 dest=/etc/mesos-master/ip
  tags: deploy

- name: Update mesos-master hostname
  template: src=mesos-master-hostname.j2 dest=/etc/mesos-master/hostname
  tags: deploy

- name: Create marathon config directory
  file: path=/etc/marathon/conf state=directory mode=0755
  tags: deploy

- name: Update marathon hostname
  template: src=mesos-master-hostname.j2 dest=/etc/marathon/conf/hostname
  tags: deploy

- name: Update marathon to mesos connection config
  template: src=mesos-zk.j2 dest=/etc/marathon/conf/master
  tags: deploy

- name: Update marathon to zookeeper connection config
  template: src=marathon-zk.j2 dest=/etc/marathon/conf/zk
  tags: deploy
  notify:
    - Stop mesos-slave
    - Restart zookeeper
    - Restart mesos-master
    - Restart marathon
