---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  apt_repository: repo='deb {{ mesosphere_apt_url }} {{ ansible_distribution_release | lower }} main' state=present

- name: Add java repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Update cache apt-get update
  apt: update_cache=yes

- name: Install master packages
  package: pkg={{ item }} state=present
  with_items:
    - python-software-properties
    - debconf-utils

- name: Accept oracle java license
  shell: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

- name: Install the latest version of java
  package: name=oracle-java8-installer state=latest

- name: Install the latest version of java default
  package: name=oracle-java8-set-default state=latest
